### ISSUE TITLE
User Story: Site navigation

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#10]
As **site visitor** I can **easily navigate around the site** so that I **easily find information I want**

### Acceptance Criteria
- user should be able to easily navigate between pages using an intuitive menu
- user can clearly see page and login status

### Tasks
- [x] create a mobile-first responsive front end
- [x] create an uncluttered navbar linking site sections
- [x] ensure navbar is always visible
- [x] ensure current user actions/choices are clearly highlighted
