### ISSUE TITLE
User Story: View detailed product info

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#11]
As **site visitor** I can **view products** so that I **find further information about products that interest me**

### Acceptance Criteria
- User should be able to easily find & view product information 
- user should be able to click to view more detailed information

### Tasks
- [x] layout products in bootstrap cards (three wide on a desktop)
- [x] card should grow or glow when user hovers mouse (clear indication)
- [x] clicking product card expands the card to show further detailed information
