### ISSUE TITLE
User Story: As Admin, create, amend or delete customers

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#24]
As **soite sdmin** I can **CRUD customers** so that I **manage my customer accounts**

### Acceptance Criteria
- User should be able to  create, view, update or delete customers

### Tasks
- [ ] Create a customer_list template & view
- [ ] create a customer_form template & view
- [ ] create a customer_confirm_delete template & view
