### ISSUE TITLE
User Story: Admin user, integrate transactions to accounting system

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#26]
As **site admin** I can **post invoices to accounting system** so that I **automatically update financial records**

### Acceptance Criteria
- User should be able to configure API data for third party accounting system

### Tasks
- [ ] Create a data map for Big Red Cloud (BRC) API
- [ ] create a data map model for customers & products
- [ ] create automated signal to push sales invoice to BRC on payment success
