### ISSUE TITLE
Site SEO

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#27]
- [x] keywords
- [x] decriptive meta tags
- [x] ensure _rel attributes on external links
- [x] create a sitemap.xml
- [x] create a robots.txt
