### ISSUE TITLE
User Story: Display friendly error pages

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#28]
As **site visitor** I can **view a friendly page in the event of an error** so that I **remain on the site with an easy way back to the home page**

### Acceptance Criteria
- In the event of a http server error, user should be shown a friendly error page with clear links back to home or contact page  

### Tasks
- [ ] Create a http error 403.html template
- [ ] Create a http error 404.html template
- [ ] Create a http error 500.html template
