### ISSUE TITLE
User Story: I would like a VAT invoice

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#35]
As **customer** I can **receive a VAT invoice** so that I **comply with tax regulations**

### Acceptance Criteria
- User receives a business VAT invoice showing VAT total for transaction & breakdown of total by VAT rate

### Tasks
- [x] add vat model and alter product & invoice tables
- [x] update shopping cart to reflect VAT on sale total
- [x] update checkout logic to calculate VAT per invoice line item
- [x] update checkout logic to calculate total VAT amt & VAT breakdown by rate code on invoice
