### ISSUE TITLE
User Story: As Admin CRUD products at front-end

### ISSUE THREAD

**Issue by davewatters** [davewatters/sectech-ci-pp5#37]
As **admin** I can **CRUD products from main screen** so that I **manage my products from the front-end**

### Acceptance Criteria
- site admin user should be able to full create, view, update or delete products from a front end control panel without need to use Django builtin /admin back-end access

### Tasks
- [x] Create a product_list template & view
- [x] create a product_form template & view
- [x] create a product_confirm_delete template & view
